export const savingsCalculatorContent = {
  title: "Calculadora de Ahorro",
  description: "Estima cuánto tiempo y dinero puedes ahorrar al automatizar las interacciones repetitivas con un agente de IA.",
  cardTitle: "Echa cuentas...",
  interactionsPerDayLabel: "Interacciones al día",
  pricePerHourLabel: "Precio por hora",
  averageDurationLabel: "Duración media (minutos)",
  resultsCardTitle: "Ahorro anual estimado",
  moneySavedLabel: "Ahorro /mes",
  hoursSavedLabel: "Horas /año",
  daysSavedLabel: "Días /año",
  breakdownTitle: "Desglose del cálculo",
  interactionsPerMonthLabel: "Interacciones al mes:",
  hoursInvestedPerMonthLabel: "Horas invertidas al mes:",
  monthlySavingsLabel: "Ahorro mensual:",
  currentMonthlyCostLabel: "Coste mensual actual:",
  hoursUnit: "horas",
  daysUnit: "días",
  minutesUnit: "min",
  showBreakdownButton: "Mostrar desglose",
  mobileModalTitle: "Tu ahorro mensual estimado",
};