export const savingsCalculatorContent = {
  title: "Calculadora de Ahorro",
  description: "Estima cuánto tiempo y dinero puedes ahorrar al automatizar las interacciones repetitivas con un agente de IA.",
  cardTitle: "Echa cuentas...",
  interactionsPerDayLabel: "Interacciones al día",
  pricePerHourLabel: "Precio por hora",
  averageDurationLabel: "Duración media (minutos)",
  resultsCardTitle: "Ahorro anual estimado",
  moneySavedLabel: "Ahorro /mes",
  hoursSavedLabel: "Horas /año",
  daysSavedLabel: "Días /año",
  breakdownTitle: "Desglose del cálculo",
  interactionsPerMonthLabel: "Interacciones al mes:",
  hoursInvestedPerMonthLabel: "Horas invertidas al mes:",
  monthlySavingsLabel: "Ahorro mensual:",
  currentMonthlyCostLabel: "Coste mensual actual:",
  estimatedAnnualCostLabel: "Coste anual aproximado:",
  estimatedInitialCostLabel: "Coste inicial aproximado:",
  hoursUnit: "horas",
  daysUnit: "días",
  minutesUnit: "min",
  showBreakdownButton: "Mostrar desglose",
  mobileModalTitle: "Tu ahorro mensual estimado",
  parameters: {
    workingHoursPerDay: 8,
    roiYears: 5,
  },
  roiSummaryCard: {
    title: "Retorno de Inversión a 5 años",
    tableHeaders: {
      year: "Año",
      cumulativeCost: "Coste Acumulado",
      cumulativeSavings: "Ahorro Acumulado",
      cumulativeRoi: "ROI Acumulado (%)",
    },
    tooltip: {
      year: "Año:",
      cumulativeRoi: "ROI Acumulado",
      cumulativeCost: "Coste Acumulado",
      cumulativeSavings: "Ahorro Acumulado",
    },
    barNames: {
      cumulativeSavings: "Ahorro Acumulado",
      cumulativeCost: "Coste Acumulado",
    },
  },
};
