export const configuratorContent = { // Updated to include savings estimation fields
  pageTitle: "Configurador",
  pageSubtitle: "Agente modular",
  pageDescription: "Personaliza tu agente seleccionando los módulos que mejor se adapten a las necesidades de tu empresa.",
  coreModulesTitle: "Módulos Core",
  coreModulesDescription: "Los módulos core son esenciales y no pueden desactivarse.",
  extraModulesTitle: "Módulos Extra",
  extraModulesPriceHint: "(500€/módulo)",
  budgetTitle: "Presupuesto",
  hideBudgetButton: "Ocultar presupuesto",
  monthlyButton: "Mensual",
  annualButton: "Anual",
  supportMaintenanceTitle: "Soporte y Mantenimiento",
  basicCoreMaintenance: "Core",
  basicMaintenanceAnnual: "4000€/año",
  basicMaintenanceMonthly: "400€/mes",
  extraMaintenanceAnnualSuffix: "€/año",
  extraMaintenanceMonthlySuffix: "€/mes",
  extraMaintenancePrefix: "Extra (",
  extraMaintenanceSuffixSingular: " módulo)",
  extraMaintenanceSuffixPlural: " módulos)",
  totalMaintenance: "Total",
  initialPayment: "Pago inicial",
  paymentTypeAnnual: "anual",
  paymentTypeMonthly: "mensual",
  paymentSupport: " (soporte)",
  hideDescription: "Ocultar descripción",
  viewDescription: "Ver descripción",
  essentialModuleTooltip: "Este módulo es esencial y no puede desactivarse",
  showBudgetButton: "Mostrar presupuesto",
  mobileShow: "Mostrar",
  mobileHide: "Ocultar",
  savingsEstimationTitle: "Estimación de Ahorro",
  savingsEstimationDescription: "Ajusta los parámetros para estimar el ahorro que tu agente puede generar.",
  interactionsPerDay: "Interacciones al día",
  hourlyCost: "Coste por hora de trabajo",
  averageDuration: "Duración media de interacción (minutos)",
  estimatedAnnualSavings: "Ahorro Anual Estimado",
  agentAnnualCost: "Coste Anual del Agente",
  paybackPeriod: "Periodo de Retorno (meses)",
  netAnnualSavings: "Ahorro Neto Anual",
};