export const configuratorContent = {
  pageSubtitle: "Agente modular",
  pageTitle: "Configurador",
  pageDescription: "Personaliza tu agente seleccionando los módulos que mejor se adapten a las necesidades de tu empresa.",
  coreModulesTitle: "Módulos Core",
  coreModulesDescription: "Los módulos core son esenciales y no pueden desactivarse.",
  extraModulesTitle: "Módulos Extra",
  extraModulesPriceHint: "(500€/módulo)",
  budgetTitle: "Presupuesto",
  supportMaintenanceTitle: "Soporte y Mantenimiento",
  annualButton: "Anual",
  monthlyButton: "Mensual",
  basicCoreMaintenance: "Básico (Core)",
  extraMaintenancePrefix: "Extra (",
  extraMaintenanceSuffixSingular: " módulo)",
  extraMaintenanceSuffixPlural: " módulos)",
  totalMaintenance: "Total mantenimiento",
  initialPayment: "Pago inicial",
  paymentTypeAnnual: "anual",
  paymentTypeMonthly: "mensual",
  paymentSupport: " (soporte)",
  hideDescription: "Ocultar descripción",
  viewDescription: "Ver descripción",
  essentialModuleTooltip: "Este módulo es esencial y no puede desactivarse",
  hideBudgetButton: "Ocultar presupuesto",
  showBudgetButton: "Mostrar presupuesto",
  mobileShow: "Mostrar",
  mobileHide: "Ocultar",
};